spring.application.name=back
spring.datasource.url=jdbc:oracle:thin:@chiao123_low?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=RESTAURANTE_USER
spring.datasource.password=Pollitos01270

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

app.jwt.secret=pon_aqui_una_clave_de_32_o_mas_caracteres_123456789
app.jwt.expiration-ms=86400000

server.port=8080