package proyecto.personal.proyectointegradorii.ui.theme
import androidx.compose.ui.graphics.Color
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val MainColor = Color(0xFFFF6A2A)
val CommentContentColor = Color(0xFFFFB494)
val CommentContainerColor = Color(0xFFFF8F5E)
val SuccessfulColor = Color(0xFF1C8C2D)
val ContentColor = Color(0xFFC0FCCA)
val ContainerColor = Color(0xFF96D6A0)
val AlertColor = Color(0xFFFF4F4F)
val BackgroundColor = Color(0xFFEDE2DD)
val BackgroundCardColor = Color(0xFFF3F3F3)
val BorderInputColor = Color(0xFFDADADA)
val TextColorDark = Color(0xFF2B2B2B)
val TextColorGray = Color(0xFF858585)
val TextColorWhite = Color(0xFFFFFFFF)
val CommentTextColor = Color(0xFFFFD6C2)
val PlaceHolderColor = Color(0xFFB3B3B3)